### ISSUE TITLE
Can Not Use The Method "from_dataset" To Index The Dataset

### ISSUE THREAD

**Issue by JoshuaMur** [tensorflow/recommenders#634]
I'm running a similar setup of the following code locally `brute_force_lots = tfrs.layers.factorized_top_k.BruteForce()
brute_force_lots.index_from_dataset(
    tf.data.Dataset.zip((lots_of_movies, lots_of_movies_embeddings))
)`
And I'm getting the error: `AttributeError: 'BruteForce' object has no attribute 'index_from_dataset'
` Which means I can not access the dataset's indices after generating them.

**Comment by patrickorlando** [comment]
What version of the library do you have installed?

**Comment by JoshuaMur** [comment]
Working with Tensorflow: '2.9.0' and Tensorflow Recommenders: 'v0.3.0'
A link on how to upgrade on Mac Silicon (M2) can feel better.

**Comment by patrickorlando** [comment]
Please upgrade tensorflow_recommenders to `0.7.3`, using pip.

**Comment by JoshuaMur** [comment]
Hey @patrickorlando Indeed a simple `pip install --upgrade tensorflow_recommeders` turns out to bring `index_from_dataset` in as method. Not screaming that error anymore. Thank to you for the hint 🙂 
Not sure why it did not install the most recent version though since I just installed tfrs not so long. But either, fighting with other errors now, one at a time.

**Comment by riyaj8888** [comment]
i am unable to upgrade the tfrs.
getting following error
tensorboard 2.10.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.3 which is incompatible.
tensorflow 2.10.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.3 which is incompatible.

**Comment by riyaj8888** [comment]
when i installed v0.7.3 i m getting following error


ImportError: cannot import name 'builder' from 'google.protobuf.internal' (/opt/conda/envs/tf/lib/python3.8/site-packages/google/protobuf/internal/__init__.py)
